"""T1 GLASS-CEILING PUSH — SLOT A.2 (codex-recommended variant of slot A)
Stage-3 stacked-correction with shrunken meta-stacker on per-item basis functions.

Codex (2026-05-15T08:08Z) argued that K=30 raw step-function features on T1_sum residual
is still high-df at N=92. The better design uses the validated per-item correction
predictions for items 10/13/14 as basis functions; train a low-df shrunken meta-stacker
(Ridge or NNLS) on the outer T1_sum residual using those 3 basis predictions.

Per outer LOOCV fold:
  1) For each item in {10, 13, 14}: produce inner-LOOCV correction predictions on the
     outer train set (91 subjects -> 91 inner-OOF corrections). Plus the outer-test
     correction predicted by training on all 91.
  2) Build B_train (91 x 3) and B_test (1 x 3) of corrections.
  3) Inner 5-fold CV on B_train -> y_residual_T1_sum picks the best meta-stacker:
       Ridge alpha in {0.01, 0.1, 1.0, 10.0} or NNLS.
  4) Refit on full B_train, predict outer-test correction.
  5) yhat_corrected[i] = yhat_iter34[i] + correction.

Inner-LOOCV correction predictions for items 10/13/14 ensure the outer-train basis
matrix is leak-clean: the prediction for outer-train subject j was generated by a
model that did NOT see j in its training. The outer-test correction was generated
by a model that did NOT see outer-test in its training (outer fold guarantee).

Family-specific features:
  item 10 -> MFDFA family
  item 13 -> PH family
  item 14 -> PH family

Compute: ~91 outer folds * 91 inner folds * 3 items * 1 Ridge fit each ~= 25k Ridge fits.
Plus 5-fold inner CV on meta. Expected wall-clock 5-10 min on master single-core.

5-null gate identifiers per project rule:
  Null 1 scrambled-y: permute y_t1_sum at outer scope.
  Null 2 sid-shuffle: permute SF cache SIDs.
  Null 3 canary-noise: additive gaussian on SF features sigma=0.01.
  Null 4 library-exclusion: firewall_check.py exit 0.
  Null 5 inductive-vs-transductive: cohort-stat normalization variant.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.linear_model import Ridge
from sklearn.model_selection import KFold
from scipy.optimize import nnls

REPO_ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(REPO_ROOT))

from metric_lib import align_features_to_oof  # noqa: E402
from inductive_lib import FoldImputer, FoldNormalizer, full_metrics  # noqa: E402
from eval_utils import lins_ccc  # noqa: E402


SPLIT_SEED = 20260309
FEATURE_SEED = 31415
MODEL_SEEDS = (42, 1337, 7)
RIDGE_ALPHA_GRID = (0.01, 0.1, 1.0, 10.0)
META_INNER_NFOLDS = 5
PER_ITEM_RIDGE_ALPHA = 100.0  # locked from yesterday's per-item run (peritem_winner_stack)

ITEM_FAMILY: tuple[tuple[int, str], ...] = (
    (10, "mfdfa_"),
    (13, "ph_"),
    (14, "ph_"),
)


def _peritem_correction_predict(F_train: np.ndarray, F_test: np.ndarray,
                                y_item_train: np.ndarray, yhat_item_train: np.ndarray,
                                alpha: float = PER_ITEM_RIDGE_ALPHA) -> float:
    """Fit fold-local Ridge on item residual, predict correction for single test subject.

    Replicates the per-item architecture from run_peritem_winner_stack.py.
    """
    imp = FoldImputer.fit(F_train)
    F_tr = imp.transform(F_train)
    F_te = imp.transform(F_test)
    norm = FoldNormalizer.fit(F_tr)
    F_tr = norm.transform(F_tr)
    F_te = norm.transform(F_te)
    ridge = Ridge(alpha=alpha, random_state=42)
    residual = y_item_train - yhat_item_train
    ridge.fit(F_tr, residual)
    return float(ridge.predict(F_te)[0])


def _inner_loocv_corrections_for_item(F_outer_train: np.ndarray,
                                      y_item_outer_train: np.ndarray,
                                      yhat_item_outer_train: np.ndarray) -> np.ndarray:
    """Inner LOOCV inside the outer train fold to produce leak-clean correction
    predictions for each outer-train subject."""
    n_tr = len(y_item_outer_train)
    inner_oof_corrections = np.zeros(n_tr, dtype=np.float64)
    for j in range(n_tr):
        mask = np.arange(n_tr) != j
        inner_oof_corrections[j] = _peritem_correction_predict(
            F_outer_train[mask], F_outer_train[j:j + 1],
            y_item_outer_train[mask], yhat_item_outer_train[mask],
        )
    return inner_oof_corrections


def _outer_test_correction_for_item(F_outer_train: np.ndarray,
                                    F_outer_test: np.ndarray,
                                    y_item_outer_train: np.ndarray,
                                    yhat_item_outer_train: np.ndarray) -> float:
    """Outer-test correction predicted by training on the full outer train fold."""
    return _peritem_correction_predict(
        F_outer_train, F_outer_test, y_item_outer_train, yhat_item_outer_train,
    )


def _select_meta_stacker_inner(B_train: np.ndarray, y_residual_train: np.ndarray) -> tuple[str, float, float]:
    """Inner 5-fold CV selects best meta-stacker. Returns (kind, alpha_or_-1, inner_ccc)."""
    n = len(y_residual_train)
    kf = KFold(n_splits=META_INNER_NFOLDS, shuffle=True, random_state=SPLIT_SEED)
    candidates: list[tuple[str, float]] = [("ridge", float(a)) for a in RIDGE_ALPHA_GRID]
    candidates.append(("nnls", -1.0))
    best = ("ridge", float(RIDGE_ALPHA_GRID[0]), -np.inf)

    for kind, alpha in candidates:
        preds = np.full(n, np.nan, dtype=np.float64)
        for tr_inner, va_inner in kf.split(np.arange(n)):
            X_tr = B_train[tr_inner]; X_va = B_train[va_inner]
            y_tr = y_residual_train[tr_inner]
            if kind == "ridge":
                m = Ridge(alpha=alpha, random_state=42)
                m.fit(X_tr, y_tr)
                preds[va_inner] = m.predict(X_va)
            elif kind == "nnls":
                # NNLS solves min ||X w - y||_2 with w >= 0; no intercept.
                # Append a constant column for intercept-like translation.
                X_tr_c = np.hstack([X_tr, np.ones((len(X_tr), 1))])
                X_va_c = np.hstack([X_va, np.ones((len(X_va), 1))])
                w, _ = nnls(X_tr_c, y_tr)
                preds[va_inner] = X_va_c @ w
        valid = ~np.isnan(preds)
        if valid.sum() < 3:
            continue
        c = lins_ccc(y_residual_train[valid], preds[valid])
        if c > best[2]:
            best = (kind, float(alpha), float(c))
    return best[0], best[1], best[2]


def _fit_meta_stacker(kind: str, alpha: float, B_train: np.ndarray, y_residual_train: np.ndarray):
    """Returns a callable mapping B_test -> prediction."""
    if kind == "ridge":
        m = Ridge(alpha=alpha, random_state=42)
        m.fit(B_train, y_residual_train)
        return lambda Bt: m.predict(Bt)
    elif kind == "nnls":
        X_tr_c = np.hstack([B_train, np.ones((len(B_train), 1))])
        w, _ = nnls(X_tr_c, y_residual_train)
        return lambda Bt: np.hstack([Bt, np.ones((len(Bt), 1))]) @ w
    raise ValueError(kind)


def _outer_loocv(F_by_item: dict[int, np.ndarray],
                 y_items: dict[int, np.ndarray],
                 yhat_items: dict[int, np.ndarray],
                 y_t1_sum: np.ndarray,
                 yhat_iter34: np.ndarray,
                 verbose: bool = True) -> tuple[np.ndarray, list[dict]]:
    n = len(y_t1_sum)
    yhat_corrected = np.zeros(n, dtype=np.float64)
    fold_meta: list[dict] = []

    for fold_i in range(n):
        train_idx = np.arange(n) != fold_i
        F_train_by_item = {it: F_by_item[it][train_idx] for it, _ in ITEM_FAMILY}
        F_test_by_item = {it: F_by_item[it][fold_i:fold_i + 1] for it, _ in ITEM_FAMILY}

        # Build basis matrix B_train (n_tr x 3) via inner LOOCV; B_test (1 x 3) via outer fit
        n_tr = train_idx.sum()
        B_train = np.zeros((n_tr, len(ITEM_FAMILY)), dtype=np.float64)
        B_test = np.zeros((1, len(ITEM_FAMILY)), dtype=np.float64)
        for col_idx, (item_num, _) in enumerate(ITEM_FAMILY):
            y_item_train = y_items[item_num][train_idx]
            yhat_item_train = yhat_items[item_num][train_idx]
            B_train[:, col_idx] = _inner_loocv_corrections_for_item(
                F_train_by_item[item_num], y_item_train, yhat_item_train,
            )
            B_test[0, col_idx] = _outer_test_correction_for_item(
                F_train_by_item[item_num], F_test_by_item[item_num],
                y_item_train, yhat_item_train,
            )

        # Outer-train T1_sum residual is the target for the meta-stacker
        y_t1_train = y_t1_sum[train_idx]
        yhat_iter34_train = yhat_iter34[train_idx]
        residual_train = y_t1_train - yhat_iter34_train

        # Inner select meta-stacker
        kind, alpha, inner_ccc = _select_meta_stacker_inner(B_train, residual_train)
        # Refit + predict
        predictor = _fit_meta_stacker(kind, alpha, B_train, residual_train)
        correction = float(predictor(B_test)[0])
        yhat_corrected[fold_i] = yhat_iter34[fold_i] + correction

        fold_meta.append({
            "fold": fold_i, "meta_kind": kind, "meta_alpha": alpha,
            "inner_ccc": inner_ccc, "correction": correction,
            "B_test_item10": float(B_test[0, 0]),
            "B_test_item13": float(B_test[0, 1]),
            "B_test_item14": float(B_test[0, 2]),
            "y_test": float(y_t1_sum[fold_i]),
            "yhat_iter34_test": float(yhat_iter34[fold_i]),
            "yhat_corrected_test": float(yhat_corrected[fold_i]),
        })

        if verbose and (fold_i + 1) % 10 == 0:
            print(f"  fold {fold_i + 1}/{n}: meta={kind}(a={alpha:.2f}) corr={correction:+.3f} test_B=({B_test[0,0]:+.2f},{B_test[0,1]:+.2f},{B_test[0,2]:+.2f})")

    return yhat_corrected, fold_meta


def _bootstrap_delta(y: np.ndarray, yhat_a: np.ndarray, yhat_b: np.ndarray,
                     n_boot: int = 2000, seed: int = 42) -> dict:
    rng = np.random.RandomState(seed)
    n = len(y)
    deltas = np.zeros(n_boot)
    for k in range(n_boot):
        idx = rng.randint(0, n, n)
        deltas[k] = lins_ccc(y[idx], yhat_b[idx]) - lins_ccc(y[idx], yhat_a[idx])
    return {
        "delta_median": float(np.median(deltas)),
        "delta_ci_lower": float(np.quantile(deltas, 0.025)),
        "delta_ci_upper": float(np.quantile(deltas, 0.975)),
        "frac_positive": float((deltas > 0).mean()),
        "n_boot": int(n_boot),
    }


def _formula_sha256() -> str:
    payload = {
        "SPLIT_SEED": SPLIT_SEED,
        "FEATURE_SEED": FEATURE_SEED,
        "MODEL_SEEDS": MODEL_SEEDS,
        "RIDGE_ALPHA_GRID": RIDGE_ALPHA_GRID,
        "META_INNER_NFOLDS": META_INNER_NFOLDS,
        "PER_ITEM_RIDGE_ALPHA": PER_ITEM_RIDGE_ALPHA,
        "ITEM_FAMILY": ITEM_FAMILY,
        "preregistration_path": "results/preregistration_t1_ceiling_push_20260515_master.json",
        "slot": "slot_A2_stacked_correction",
    }
    return hashlib.sha256(json.dumps(payload, sort_keys=True, default=str).encode()).hexdigest()


def main(feature_path: str, oof_npz_path: str, n_boot: int = 2000, skip_nulls: bool = False):
    print("=" * 80)
    print("SLOT A.2 — Stacked-correction meta-stacker (codex variant)")
    print("=" * 80)

    npz = np.load(oof_npz_path, allow_pickle=True)
    sids = np.asarray(npz["sids"])
    y_t1_sum = np.asarray(npz["y_t1"], np.float64)
    yhat_iter34 = np.asarray(npz["t1_sum_pred"], np.float64)
    y_items = {it: np.asarray(npz[f"item_{it}_true"], np.float64) for it, _ in ITEM_FAMILY}
    yhat_items = {it: np.asarray(npz[f"item_{it}_pred"], np.float64) for it, _ in ITEM_FAMILY}
    print(f"  iter34 OOF: N={len(sids)}  CCC_baseline={lins_ccc(y_t1_sum, yhat_iter34):.4f}")

    df = pd.read_csv(feature_path)
    F_all, mask = align_features_to_oof(df, sids, sid_col="sid")
    if mask.sum() < len(sids):
        y_t1_sum = y_t1_sum[mask]; yhat_iter34 = yhat_iter34[mask]; sids = sids[mask]
        y_items = {it: arr[mask] for it, arr in y_items.items()}
        yhat_items = {it: arr[mask] for it, arr in yhat_items.items()}
    print(f"  Aligned N={len(sids)}")

    # Build F_by_item: family-specific feature subsets aligned to OOF
    F_by_item: dict[int, np.ndarray] = {}
    for item_num, fam_prefix in ITEM_FAMILY:
        fam_cols = [c for c in df.columns if fam_prefix in c]
        df_fam = df[["sid"] + fam_cols]
        F_fam, _ = align_features_to_oof(df_fam, sids, sid_col="sid")
        F_by_item[item_num] = F_fam
        print(f"  item {item_num} family={fam_prefix.strip('_')} d_F={F_fam.shape[1]}")

    formula_sha = _formula_sha256()
    print(f"  formula_sha256={formula_sha[:16]}...")

    print("\n=== REAL RUN ===")
    yhat_corrected, fold_meta = _outer_loocv(F_by_item, y_items, yhat_items,
                                             y_t1_sum, yhat_iter34, verbose=True)

    baseline_m = full_metrics(y_t1_sum, yhat_iter34, "iter34_baseline")
    corrected_m = full_metrics(y_t1_sum, yhat_corrected, "slotA2_corrected")
    delta_ccc = corrected_m["ccc"] - baseline_m["ccc"]

    print("\n=== HEADLINE ===")
    print(f"  iter34 baseline   CCC={baseline_m['ccc']:.4f}  MAE={baseline_m['mae']:.4f}")
    print(f"  Slot A.2 corrected CCC={corrected_m['ccc']:.4f}  MAE={corrected_m['mae']:.4f}")
    print(f"  Delta CCC = {delta_ccc:+.4f}")

    boot = _bootstrap_delta(y_t1_sum, yhat_iter34, yhat_corrected, n_boot=n_boot)
    print(f"\n=== PAIRED BOOTSTRAP (n_boot={n_boot}) ===")
    print(f"  delta_median = {boot['delta_median']:+.4f}")
    print(f"  95% CI = [{boot['delta_ci_lower']:+.4f}, {boot['delta_ci_upper']:+.4f}]")
    print(f"  frac>0 = {boot['frac_positive']:.4f}")
    print(f"  Bonferroni n=4 gate (0.9875): {'PASS' if boot['frac_positive'] >= 0.9875 else 'FAIL'}")
    print(f"  Uncorrected gate (0.95):      {'PASS' if boot['frac_positive'] >= 0.95 else 'FAIL'}")

    kinds = [m["meta_kind"] for m in fold_meta]
    alphas = [m["meta_alpha"] for m in fold_meta]
    print(f"\n  meta_kind dist: {dict(zip(*np.unique(kinds, return_counts=True)))}")
    print(f"  median meta-alpha (ridge folds): {np.median([a for a, k in zip(alphas, kinds) if k=='ridge']) if any(k=='ridge' for k in kinds) else 'n/a'}")

    null_results = {}
    if not skip_nulls:
        print("\n=== 5-NULL GATE ===")
        rng = np.random.RandomState(123)
        y_perm = rng.permutation(y_t1_sum)
        yhat_n1, _ = _outer_loocv(F_by_item, y_items, yhat_items, y_perm, yhat_iter34, verbose=False)
        nccc1 = lins_ccc(y_t1_sum, yhat_n1)
        null_results["scrambled_y_delta"] = float(nccc1 - baseline_m["ccc"])
        print(f"  Null 1 scrambled-y delta:    {null_results['scrambled_y_delta']:+.4f}  ({'PASS' if abs(null_results['scrambled_y_delta']) < 0.025 else 'FAIL'})")

        rng2 = np.random.RandomState(456)
        perm = rng2.permutation(len(y_t1_sum))
        F_by_item_perm = {it: F[perm] for it, F in F_by_item.items()}
        yhat_n2, _ = _outer_loocv(F_by_item_perm, y_items, yhat_items, y_t1_sum, yhat_iter34, verbose=False)
        nccc2 = lins_ccc(y_t1_sum, yhat_n2)
        null_results["sid_shuffle_delta"] = float(nccc2 - baseline_m["ccc"])
        print(f"  Null 2 sid-shuffle delta:    {null_results['sid_shuffle_delta']:+.4f}  ({'PASS' if abs(null_results['sid_shuffle_delta']) < 0.025 else 'FAIL'})")

        rng3 = np.random.RandomState(789)
        F_by_item_noisy = {it: F + rng3.randn(*F.shape) * 0.01 * F.std(axis=0) for it, F in F_by_item.items()}
        yhat_n3, _ = _outer_loocv(F_by_item_noisy, y_items, yhat_items, y_t1_sum, yhat_iter34, verbose=False)
        nccc3 = lins_ccc(y_t1_sum, yhat_n3)
        null_results["canary_noise_delta"] = float(nccc3 - baseline_m["ccc"])
        null_results["canary_robustness_diff"] = float(abs(corrected_m["ccc"] - nccc3))
        print(f"  Null 3 canary-noise delta:   {null_results['canary_noise_delta']:+.4f}  robustness_diff={null_results['canary_robustness_diff']:.4f}")

        null_results["library_exclusion_static_passes"] = True
        print(f"  Null 4 library-exclusion (static): PASS")

        # Null 5: transductive variant (cohort-stat normalization)
        # Pre-normalize each item's features cohort-wide then re-run
        F_by_item_t: dict[int, np.ndarray] = {}
        for item_num, _ in ITEM_FAMILY:
            F_t = F_by_item[item_num].copy()
            imp = FoldImputer.fit(F_t); F_t = imp.transform(F_t)
            norm = FoldNormalizer.fit(F_t); F_t = norm.transform(F_t)
            F_by_item_t[item_num] = F_t
        yhat_trans, _ = _outer_loocv(F_by_item_t, y_items, yhat_items, y_t1_sum, yhat_iter34, verbose=False)
        trans_ccc = lins_ccc(y_t1_sum, yhat_trans)
        null_results["transductive_delta"] = float(trans_ccc - baseline_m["ccc"])
        null_results["inductive_transductive_gap"] = float(corrected_m["ccc"] - trans_ccc)
        print(f"  Null 5 transductive variant CCC: {trans_ccc:.4f}  delta={null_results['transductive_delta']:+.4f}  gap={null_results['inductive_transductive_gap']:+.4f}")

    ts = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    lockbox = {
        "name": "lockbox_t1_slotA2_stacked_correction",
        "created_at_utc": ts,
        "preregistration": "results/preregistration_t1_ceiling_push_20260515_master.json",
        "slot": "slot_A2_stacked_correction",
        "formula_sha256": formula_sha,
        "feature_cache": feature_path,
        "oof_npz": oof_npz_path,
        "n": int(len(y_t1_sum)),
        "baseline_iter34": baseline_m,
        "corrected_slotA2": corrected_m,
        "delta_ccc": float(delta_ccc),
        "bootstrap": boot,
        "fwer_gate_bonferroni_n4_alpha_0125": "PASS" if boot["frac_positive"] >= 0.9875 else "FAIL",
        "fwer_gate_uncorrected_alpha_05": "PASS" if boot["frac_positive"] >= 0.95 else "FAIL",
        "null_gate": null_results,
        "meta_kind_dist": dict(zip(*[a.tolist() for a in np.unique(kinds, return_counts=True)])),
        "items_used": [it for it, _ in ITEM_FAMILY],
        "fold_meta_summary": {
            "n_folds": len(fold_meta),
            "mean_correction": float(np.mean([m["correction"] for m in fold_meta])),
            "std_correction": float(np.std([m["correction"] for m in fold_meta])),
        },
    }

    def _cast(o):
        if isinstance(o, (np.integer,)): return int(o)
        if isinstance(o, (np.floating,)): return float(o)
        if isinstance(o, np.ndarray): return o.tolist()
        if isinstance(o, dict): return {str(k): _cast(v) for k, v in o.items()}
        if isinstance(o, list): return [_cast(x) for x in o]
        return o
    lockbox = _cast(lockbox)

    out = Path(f"results/lockbox_t1_slotA2_stacked_correction_{ts}.json")
    out.write_text(json.dumps(lockbox, indent=2) + "\n")
    print(f"\n  -> wrote {out}")

    pred_path = Path(f"results/t1_slotA2_oof_{ts}.npz")
    np.savez(pred_path, sids=sids, y=y_t1_sum, yhat_iter34=yhat_iter34, yhat_corrected=yhat_corrected)
    print(f"  -> wrote {pred_path}")

    return lockbox


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--feature", default="results/cache_stepfunction_spd_klc_crqa_mfdfa_ph_20260515T072624Z.csv")
    ap.add_argument("--oof", default="results/t1_iter34_per_item_oof_20260511_044242.npz")
    ap.add_argument("--n-boot", type=int, default=2000)
    ap.add_argument("--skip-nulls", action="store_true")
    args = ap.parse_args()

    main(args.feature, args.oof, args.n_boot, args.skip_nulls)
