"""Leak-safe Ridge meta-stacking helpers for T3 iter4.

The contract:
  - Inputs are LOOCV out-of-fold (OOF) predictions from frozen base models.
    Each base OOF[i] was generated by training the base on {all subjects} \\ {i}.
  - The meta-stack uses ONLY base OOFs as features.
  - Outer LOOCV holds out subject k; inner LOOCV on the remaining N-1 picks
    the Ridge alpha. No alpha tuning ever sees the held-out fold's label.

Standard "stacking-on-OOF" caveat: subject k's true label was used by base
training to produce OOF[j] for j != k. This 2nd-order leakage is bounded by
the negative-control battery in `null_meta_*` (scrambled label, canary
feature, permuted base), all of which must drop CCC to ~0.

Pure logic — no I/O, no dataset assumptions. Reusable by future stacks.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Sequence

import numpy as np
from sklearn.linear_model import Ridge
from sklearn.model_selection import KFold

ALPHA_GRID_DEFAULT: tuple[float, ...] = (0.01, 0.1, 1.0, 10.0, 100.0)


# ── core: nested LOOCV with inner-LOOCV alpha selection ──────────────────────


def _select_alpha_inner_loocv(
    X_train: np.ndarray, y_train: np.ndarray, alpha_grid: Sequence[float]
) -> float:
    """Pick Ridge alpha by minimising inner-LOOCV MSE on the training fold."""
    n = len(y_train)
    best_alpha = alpha_grid[0]
    best_mse = np.inf
    for alpha in alpha_grid:
        inner_preds = np.zeros(n)
        for j in range(n):
            mask = np.ones(n, dtype=bool)
            mask[j] = False
            m = Ridge(alpha=alpha, fit_intercept=True)
            m.fit(X_train[mask], y_train[mask])
            inner_preds[j] = float(m.predict(X_train[j : j + 1])[0])
        mse = float(np.mean((inner_preds - y_train) ** 2))
        if mse < best_mse:
            best_mse = mse
            best_alpha = float(alpha)
    return best_alpha


def nested_loocv_ridge(
    X: np.ndarray,
    y: np.ndarray,
    alpha_grid: Sequence[float] = ALPHA_GRID_DEFAULT,
) -> tuple[np.ndarray, list[float]]:
    """Outer-LOOCV Ridge with inner-LOOCV alpha selection. Returns (preds, alphas)."""
    n = len(y)
    preds = np.zeros(n)
    alphas: list[float] = []
    for k in range(n):
        train_mask = np.ones(n, dtype=bool)
        train_mask[k] = False
        Xtr, ytr = X[train_mask], y[train_mask]
        alpha = _select_alpha_inner_loocv(Xtr, ytr, alpha_grid)
        alphas.append(alpha)
        m = Ridge(alpha=alpha, fit_intercept=True)
        m.fit(Xtr, ytr)
        preds[k] = float(m.predict(X[k : k + 1])[0])
    return preds, alphas


# ── 5-fold screening (cheap, re-runnable) ────────────────────────────────────


def screen_stack_kfold(
    X: np.ndarray,
    y: np.ndarray,
    alpha_grid: Sequence[float] = ALPHA_GRID_DEFAULT,
    n_splits: int = 5,
    seed: int = 42,
) -> tuple[np.ndarray, list[float]]:
    """K-fold outer with inner-LOOCV alpha selection on each train fold."""
    kf = KFold(n_splits=n_splits, shuffle=True, random_state=seed)
    preds = np.zeros(len(y))
    alphas: list[float] = []
    for tr, te in kf.split(X):
        Xtr, ytr = X[tr], y[tr]
        alpha = _select_alpha_inner_loocv(Xtr, ytr, alpha_grid)
        alphas.append(alpha)
        m = Ridge(alpha=alpha, fit_intercept=True)
        m.fit(Xtr, ytr)
        preds[te] = m.predict(X[te])
    return preds, alphas


# ── residual augmentation: anchor on a base, fit Ridge only on the residual ──
#
# Intuition: when one base predictor is already well-calibrated to the target
# (B_hy on T3), direct Ridge over (B_hy, B_T1, B_18) suffers per-fold noise
# in the B_hy coefficient that can crater CCC. Pinning the B_hy coefficient
# to 1 and only learning the AUGMENTATION (Ridge on residual ~ other bases)
# is strictly better when the anchor is calibrated. This is "delta stacking".


def screen_residual_stack_kfold(
    X: np.ndarray,
    y: np.ndarray,
    anchor_idx: int,
    augment_idx: Sequence[int],
    alpha_grid: Sequence[float] = ALPHA_GRID_DEFAULT,
    n_splits: int = 5,
    seed: int = 42,
) -> tuple[np.ndarray, list[float]]:
    """5-fold residual augmentation. preds = X[:, anchor_idx] + Ridge(residual ~ X[:, augment_idx])."""
    kf = KFold(n_splits=n_splits, shuffle=True, random_state=seed)
    preds = np.zeros(len(y))
    alphas: list[float] = []
    augment_idx = list(augment_idx)
    for tr, te in kf.split(X):
        anchor_tr = X[tr, anchor_idx]
        anchor_te = X[te, anchor_idx]
        residual_tr = y[tr] - anchor_tr
        Xa_tr = X[np.ix_(tr, augment_idx)]
        Xa_te = X[np.ix_(te, augment_idx)]
        alpha = _select_alpha_inner_loocv(Xa_tr, residual_tr, alpha_grid)
        alphas.append(alpha)
        m = Ridge(alpha=alpha, fit_intercept=True)
        m.fit(Xa_tr, residual_tr)
        residual_pred = m.predict(Xa_te)
        preds[te] = anchor_te + residual_pred
    return preds, alphas


def loocv_residual_stack_ridge(
    X: np.ndarray,
    y: np.ndarray,
    anchor_idx: int,
    augment_idx: Sequence[int],
    alpha_grid: Sequence[float] = ALPHA_GRID_DEFAULT,
) -> tuple[np.ndarray, list[float]]:
    """Outer-LOOCV residual augmentation with inner-LOOCV alpha selection."""
    n = len(y)
    preds = np.zeros(n)
    alphas: list[float] = []
    augment_idx = list(augment_idx)
    for k in range(n):
        train_mask = np.ones(n, dtype=bool)
        train_mask[k] = False
        anchor_tr = X[train_mask, anchor_idx]
        anchor_te = X[k, anchor_idx]
        residual_tr = y[train_mask] - anchor_tr
        Xa_tr = X[np.ix_(np.where(train_mask)[0], augment_idx)]
        Xa_te = X[k : k + 1][:, augment_idx]
        alpha = _select_alpha_inner_loocv(Xa_tr, residual_tr, alpha_grid)
        alphas.append(alpha)
        m = Ridge(alpha=alpha, fit_intercept=True)
        m.fit(Xa_tr, residual_tr)
        residual_pred = float(m.predict(Xa_te)[0])
        preds[k] = float(anchor_te) + residual_pred
    return preds, alphas


# ── 5-null gate (META level) ─────────────────────────────────────────────────
# All four nulls run the SAME outer protocol as the real screen — the only
# thing changed is the input. Every null must drop CCC to ~0 (or to baseline,
# in the "permuted-base" case).


def null_meta_scrambled_label(
    X: np.ndarray,
    y: np.ndarray,
    alpha_grid: Sequence[float] = ALPHA_GRID_DEFAULT,
    n_splits: int = 5,
    seed: int = 42,
) -> np.ndarray:
    """Shuffle y once, then run the same screen. Expected outer CCC ≈ 0."""
    rng = np.random.RandomState(seed)
    y_shuf = y.copy()
    rng.shuffle(y_shuf)
    preds, _ = screen_stack_kfold(X, y_shuf, alpha_grid, n_splits, seed)
    return preds


def null_meta_canary_feature(
    X: np.ndarray,
    y: np.ndarray,
    alpha_grid: Sequence[float] = ALPHA_GRID_DEFAULT,
    n_splits: int = 5,
    seed: int = 42,
) -> np.ndarray:
    """Append a random column to X. The meta should ignore it (no useful signal).
    Stack CCC should match the no-canary screen — if it improves, the meta is
    over-fitting to noise."""
    rng = np.random.RandomState(seed + 1)
    canary = rng.randn(len(y), 1)
    X_aug = np.hstack([X, canary])
    preds, _ = screen_stack_kfold(X_aug, y, alpha_grid, n_splits, seed)
    return preds


def null_meta_permuted_base(
    X: np.ndarray,
    y: np.ndarray,
    base_idx: int,
    alpha_grid: Sequence[float] = ALPHA_GRID_DEFAULT,
    n_splits: int = 5,
    seed: int = 42,
) -> np.ndarray:
    """Permute one base column across subjects. Stack CCC should DROP to the
    score achievable by the remaining bases — proves the permuted base
    contributed real signal (not just an artefact of being in the matrix)."""
    rng = np.random.RandomState(seed + 2)
    X_perm = X.copy()
    perm = rng.permutation(len(y))
    X_perm[:, base_idx] = X[perm, base_idx]
    preds, _ = screen_stack_kfold(X_perm, y, alpha_grid, n_splits, seed)
    return preds


def null_meta_transductive(
    X: np.ndarray,
    y: np.ndarray,
    alpha: float = 1.0,
) -> np.ndarray:
    """Fit Ridge on ALL data (incl. the eval rows). Sanity check that the
    architecture *can* learn — should give CCC near the upper bound."""
    m = Ridge(alpha=alpha, fit_intercept=True)
    m.fit(X, y)
    return m.predict(X)


# ── small data class for screening rows ──────────────────────────────────────


@dataclass(frozen=True)
class ScreenRow:
    config: str
    bases: tuple[str, ...]
    n: int
    seed: int
    ccc: float
    mae: float
    r: float
    alpha_mode: str  # "median" or "list"
    alpha_value: float
    n_splits: int
